/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package randomasterdeskapp.pages;

// Importing JFrame class from javax.swing package for creating GUI windows.
import javax.swing.JFrame;

// Importing JOptionPane class from javax.swing package for displaying dialog boxes.
import javax.swing.JOptionPane;

// Importing ListScholarsClickListener class from randomasterdeskapp.backend package
// to access the functionality of handling click events for the list of scholars.
import randomasterdeskapp.backend.ListScholarsClickListener;

// Importing SQLException class from java.sql package to handle SQL exceptions.
import java.sql.SQLException;

// Importing JTable class from javax.swing package for displaying tabular data.
import javax.swing.JTable;

// Importing Randomizer class from randomasterdeskapp.backend.TableArrangement package
// to access the functionality of table arrangement randomization.
import randomasterdeskapp.backend.TableArrangement.Randomizer;

// Importing ProfileController class from randomasterdeskapp.backend.profilebackend package
// to access the functionality of the backend profile backend in the current code file.
import randomasterdeskapp.backend.profilebackend.ProfileController;

// Importing List interface from java.util package to work with lists.
import java.util.List;

// Importing DefaultTableModel class from javax.swing.table package for managing table data.
import javax.swing.table.DefaultTableModel;

// Importing JTextField class from javax.swing package for text input.
import javax.swing.JTextField;

/**
 *
 * @author Student Admin
 */
public class TableArrangements extends javax.swing.JFrame {

    private JTable jTableListOfScholars;
    private JTable jTableArrangement;
    private DefaultTableModel tableModel;

    public TableArrangements() {
        initComponents();
        jTableListOfScholars = new JTable();
        jTableArrangement = new JTable();
        tableModel = new DefaultTableModel();
        jTableArrangement.setModel(tableModel);
    }

    public JTextField getTextFieldTableArrangementTitle() {
        return TextFieldTableArrangementTitle;
    }

    public JTextField getTextFieldTableSize() {
        return TextFieldTableSize;
    }

    public JTextField getTextFieldTableName() {
        return TextFieldTableName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelHomeinTasking = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelProfileinTasking = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelListOfScholarinTasking = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelTaskingRandomizerinAdmin1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButtonGenerate1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TextFieldTableArrangementTitle = new javax.swing.JTextField();
        TextFieldTableName = new javax.swing.JTextField();
        TextFieldTableSize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/deleteicon.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("    Tasking Name");
        jLabel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("    Tasking level");
        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("    Members per Group");
        jLabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabelHomeinTasking.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelHomeinTasking.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeinTasking.setText("Home");
        jLabelHomeinTasking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeinTaskingMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/logowhite.png"))); // NOI18N

        jLabelLogout.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setText("Logout");
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/profileicon.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/logouticon.png"))); // NOI18N

        jLabelProfileinTasking.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelProfileinTasking.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileinTasking.setText("Profile");
        jLabelProfileinTasking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProfileinTaskingMouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/homewhite.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("Table Assignment Tool");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/tableblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/listwhite.png"))); // NOI18N

        jLabelListOfScholarinTasking.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelListOfScholarinTasking.setForeground(new java.awt.Color(255, 255, 255));
        jLabelListOfScholarinTasking.setText("View List of Scholars");
        jLabelListOfScholarinTasking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelListOfScholarinTaskingMouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/randomizeicon.png"))); // NOI18N

        jLabelTaskingRandomizerinAdmin1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelTaskingRandomizerinAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTaskingRandomizerinAdmin1.setText("Tasking Randomizer");
        jLabelTaskingRandomizerinAdmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTaskingRandomizerinAdmin1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTaskingRandomizerinAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHomeinTasking, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelProfileinTasking, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelListOfScholarinTasking, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelHomeinTasking)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProfileinTasking)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabelTaskingRandomizerinAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelListOfScholarinTasking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(9, 9, 9))
                    .addComponent(jLabelLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 2, true));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setText("Effortlessly organize your seat ");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel21.setText(" with our Table Assignment Tool ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/icon1.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("File Name:");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setText("Table Name:");

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel32.setText("Number of Scholars per Table");

        jButtonGenerate1.setBackground(new java.awt.Color(51, 153, 255));
        jButtonGenerate1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonGenerate1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenerate1.setText("Generate");
        jButtonGenerate1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 102), 3, true));
        jButtonGenerate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerate1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel13.setText("Table Assignments Information");

        TextFieldTableArrangementTitle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextFieldTableArrangementTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        TextFieldTableName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextFieldTableName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        TextFieldTableSize.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextFieldTableSize.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/seatplan.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldTableArrangementTitle)
                            .addComponent(jButtonGenerate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldTableSize)
                            .addComponent(TextFieldTableName)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)))
                .addGap(119, 119, 119))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldTableArrangementTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldTableSize, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonGenerate1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelListOfScholarinTaskingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelListOfScholarinTaskingMouseClicked
        if (evt.getClickCount() == 1) { // check if the label is clicked once
            try {
                // create a new instance of ListOfScholars frame
                // create a new instance of ListOfScholars frame
                ListOfScholar listOfScholarFrame = new ListOfScholar(jTableListOfScholars);
                // create a new instance of ListScholarsClickListener and pass the jTableListOfScholars component
                ListScholarsClickListener listScholarsClickListener = new ListScholarsClickListener(listOfScholarFrame.getjTableListOfScholars());
                // call the onClick method to populate the jTableListOfScholars with the list of scholars data
                listScholarsClickListener.onClick();
                // set the ListOfScholars frame visible to the user
                listOfScholarFrame.setVisible(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabelListOfScholarinTaskingMouseClicked

    private void jLabelProfileinTaskingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProfileinTaskingMouseClicked
        // Calling the openUserProfile method from the ProfileController class to view user profile
        ProfileController.openUserProfile();
    }//GEN-LAST:event_jLabelProfileinTaskingMouseClicked

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        // Display a confirmation dialog box
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            // Redirect to login
            // Assuming that "login" is the name of your login JFrame
            JFrame login = new LoginPage();
            login.setVisible(true);

            // Close the current JFrame
            // Assuming that "currentFrame" is the name of your current JFrame
            this.dispose();
        } else {
            // Admin clicked "no", do nothing
            return;
        }
    }//GEN-LAST:event_jLabelLogoutMouseClicked

    private void jLabelHomeinTaskingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeinTaskingMouseClicked
        JFrame adminHome = new AdminHome();
        adminHome.setVisible(true);

        // Close the current JFrame
        // Assuming that "currentFrame" is the name of your current JFrame
        this.dispose();
    }//GEN-LAST:event_jLabelHomeinTaskingMouseClicked

    private void jButtonGenerate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerate1ActionPerformed

        // Get the table arrangement title, size, and name inputs
        String tableArrangementTitle = TextFieldTableArrangementTitle.getText();
        String tableSizeInput = TextFieldTableSize.getText();
        String tableName = TextFieldTableName.getText();

        // Check if the table size is empty
        if (tableSizeInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input a table size.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Check if the table name is empty
        if (tableName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input a table name.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int tableSize;
        try {
            tableSize = Integer.parseInt(tableSizeInput);

            // Check if the table size is negative
            if (tableSize <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a positive integer for the table size.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid table size format. Please enter a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get the number of scholars in the database
        int numScholars = Randomizer.getNumScholars();

        // Check if the distribution is fair
        if (numScholars % tableSize != 0) {
            String errorMessage = "The number of scholars is not evenly divisible by the table size. There might be tables that do not consist of " + tableSize + " members."
                    + "\nAre you sure you want to proceed?";
            int choice = JOptionPane.showConfirmDialog(this, errorMessage, "Confirmation", JOptionPane.YES_NO_OPTION);
            if (choice != JOptionPane.YES_OPTION) {
                return;
            }
        } else {
            // Create a confirmation message
            String confirmationMessage = "Are you sure you want to Randomize " + numScholars
                    + " scholars into " + tableSize + " members per table?";
            // Display a confirmation dialog
            int choice = JOptionPane.showConfirmDialog(this, confirmationMessage, "Confirmation", JOptionPane.YES_NO_OPTION);
            if (choice != JOptionPane.YES_OPTION) {
                return;
            }
        }

        // Generate the groupings of scholars
        List<List<String>> groupings = Randomizer.generateGroupings(tableSize);

        // Clear the existing table data
        tableModel.setRowCount(0);
        tableModel.setColumnCount(0);

        // Add the new columns and rows
        for (int i = 0; i < groupings.size(); i++) {
            List<String> table = groupings.get(i);
            if (!table.isEmpty()) {
                // Create the column name based on the table name and number
                String columnName = tableName.substring(0, 1).toUpperCase() + tableName.substring(1).toLowerCase() + " " + (i + 1);
                tableModel.addColumn(columnName, table.toArray());
            }
        }

            // Update the title of the table arrangement window
            // Create a new instance of TableArrangements1, passing the tableSize value
            TableArrangements1 tableArrangements1Frame = new TableArrangements1(tableModel, tableSize, tableName, tableArrangementTitle);
            tableArrangements1Frame.setTitle(tableArrangementTitle);

            // Make the table arrangement window visible
            tableArrangements1Frame.setVisible(true);
        


    }//GEN-LAST:event_jButtonGenerate1ActionPerformed

    private void jLabelTaskingRandomizerinAdmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaskingRandomizerinAdmin1MouseClicked

        JFrame taskingRandomizer = new TaskingRandomizer();
        taskingRandomizer.setVisible(true);

        // Close the current JFrame
        this.dispose();
    }//GEN-LAST:event_jLabelTaskingRandomizerinAdmin1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        JFrame tableAssignmentTool = new TableArrangements(); //  initialize the JFrame
        tableAssignmentTool.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldTableArrangementTitle;
    private javax.swing.JTextField TextFieldTableName;
    private javax.swing.JTextField TextFieldTableSize;
    private javax.swing.JButton jButtonGenerate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelHomeinTasking;
    private javax.swing.JLabel jLabelListOfScholarinTasking;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelProfileinTasking;
    private javax.swing.JLabel jLabelTaskingRandomizerinAdmin1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
