/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package randomasterdeskapp.pages;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Statement;
import randomasterdeskapp.backend.DatabaseConnection;
import randomasterdeskapp.backend.ListScholarsClickListener;
import randomasterdeskapp.backend.taskingrandomizer.SaveandExportBackend;
import randomasterdeskapp.backend.Scholar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import randomasterdeskapp.backend.profilebackend.ProfileController;

/**
 *
 * @author Student Admin
 */
public class TaskingRandomizer extends javax.swing.JFrame {

    private final JTable jTableListOfScholars;

    List<String> columns = new ArrayList<>();
    List<Scholar> scholars = new ArrayList<>();
    ArrayList<String> kitchen = new ArrayList<>();
    ArrayList<String> hallway = new ArrayList<>();
    ArrayList<String> dining = new ArrayList<>();
    ArrayList<String> comlab = new ArrayList<>();
    ArrayList<String> fgarden = new ArrayList<>();
    ArrayList<String> bgarden = new ArrayList<>();
    ArrayList<String> laundry = new ArrayList<>();
    ArrayList<String> courtyard = new ArrayList<>();
    ArrayList<String> office = new ArrayList<>();
    ArrayList<String> dishwashing = new ArrayList<>();

    public TaskingRandomizer() {
        initComponents();
        jTableListOfScholars = new JTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelHomeinTasking = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelProfileinTasking = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelListOfScholarinTasking = new javax.swing.JLabel();
        jLabelTableAssignmentTool = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonRandomize = new javax.swing.JButton();
        jLabelKitchen = new javax.swing.JLabel();
        jLabelDishwashing = new javax.swing.JLabel();
        jLabelDining = new javax.swing.JLabel();
        jLabelHallway = new javax.swing.JLabel();
        jLabelLaundry = new javax.swing.JLabel();
        jLabelBackGarden = new javax.swing.JLabel();
        jLabelFrontGarden = new javax.swing.JLabel();
        jLabelCourtyard = new javax.swing.JLabel();
        jLabelComlab = new javax.swing.JLabel();
        jLabelStaffOffice = new javax.swing.JLabel();
        jTextFieldKitchenSize1 = new javax.swing.JTextField();
        jTextFieldHallwaySize = new javax.swing.JTextField();
        jTextFieldDishwashingSize = new javax.swing.JTextField();
        jTextFieldDiningSize = new javax.swing.JTextField();
        jTextFieldFrontGardenSize = new javax.swing.JTextField();
        jTextFieldLaundrySize1 = new javax.swing.JTextField();
        jTextFieldBackGardenSize1 = new javax.swing.JTextField();
        jTextFieldStaffSize = new javax.swing.JTextField();
        jTextFieldCourtyardSize1 = new javax.swing.JTextField();
        jTextFieldComlabSize1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTaskingRandomizer = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButtonExportandSave = new javax.swing.JButton();
        jLabeltaskingTitle = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/deleteicon.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("    Tasking Name");
        jLabel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("    Tasking level");
        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("    Members per Group");
        jLabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabelHomeinTasking.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelHomeinTasking.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeinTasking.setText("Home");
        jLabelHomeinTasking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeinTaskingMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/logowhite.png"))); // NOI18N

        jLabelLogout.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setText("Logout");
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/profileicon.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/logouticon.png"))); // NOI18N

        jLabelProfileinTasking.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelProfileinTasking.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileinTasking.setText("Profile");
        jLabelProfileinTasking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProfileinTaskingMouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/homewhite.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("Tasking Randomizer");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/randomizeblackicon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18))
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/listwhite.png"))); // NOI18N

        jLabelListOfScholarinTasking.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelListOfScholarinTasking.setForeground(new java.awt.Color(255, 255, 255));
        jLabelListOfScholarinTasking.setText("View List of Scholars");
        jLabelListOfScholarinTasking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelListOfScholarinTaskingMouseClicked(evt);
            }
        });

        jLabelTableAssignmentTool.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelTableAssignmentTool.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTableAssignmentTool.setText("Table Assignment Tool");
        jLabelTableAssignmentTool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTableAssignmentToolMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/randomasterdeskapp/img/tableassign.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelHomeinTasking, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProfileinTasking, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTableAssignmentTool, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelListOfScholarinTasking, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelHomeinTasking)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProfileinTasking)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelTableAssignmentTool, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelListOfScholarinTasking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(9, 9, 9))
                    .addComponent(jLabelLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jButtonRandomize.setBackground(new java.awt.Color(51, 153, 255));
        jButtonRandomize.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonRandomize.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRandomize.setText("Randomize");
        jButtonRandomize.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 102), 3, true));
        jButtonRandomize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRandomizeMouseClicked(evt);
            }
        });
        jButtonRandomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomizeActionPerformed(evt);
            }
        });

        jLabelKitchen.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelKitchen.setText("Kitchen:");

        jLabelDishwashing.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelDishwashing.setText("Dishwashing:");

        jLabelDining.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelDining.setText("Dining & Windows:");

        jLabelHallway.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelHallway.setText("Hallway & Corridor: ");

        jLabelLaundry.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelLaundry.setText("Laundry:");

        jLabelBackGarden.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelBackGarden.setText("Back Garden:");

        jLabelFrontGarden.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelFrontGarden.setText("Front Garden:");

        jLabelCourtyard.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelCourtyard.setText("Courtyard: ");

        jLabelComlab.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelComlab.setText("Comlab & Aircon:");

        jLabelStaffOffice.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelStaffOffice.setText("Staff's Office");

        jTextFieldKitchenSize1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldHallwaySize.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldDishwashingSize.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldDiningSize.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldFrontGardenSize.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldLaundrySize1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldBackGardenSize1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldStaffSize.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldCourtyardSize1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTextFieldComlabSize1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTableTaskingRandomizer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KITCHEN", "DISHWASHING", "DINING&WINDOWS", "HALLWAY & CORRIDOR", "LAUNDRY", "STAFF OFFICE", "COURTYARD", "BACK GARDEN", "FRONT GARDEN", "COMLAB & AIRCON"
            }
        ));
        jScrollPane1.setViewportView(jTableTaskingRandomizer);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel13.setText("Tasking Information");

        jButtonExportandSave.setBackground(new java.awt.Color(255, 204, 51));
        jButtonExportandSave.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonExportandSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExportandSave.setText("Export");
        jButtonExportandSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 102), 3, true));
        jButtonExportandSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExportandSaveMouseClicked(evt);
            }
        });
        jButtonExportandSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportandSaveActionPerformed(evt);
            }
        });

        jLabeltaskingTitle.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabeltaskingTitle.setText("Please Input Tasking Sizes ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelDining, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelLaundry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelHallway, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelBackGarden, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelCourtyard, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelFrontGarden, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelComlab, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelStaffOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelDishwashing, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelKitchen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldKitchenSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldDishwashingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldDiningSize, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldHallwaySize, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldLaundrySize1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldBackGardenSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCourtyardSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldComlabSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldStaffSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldFrontGardenSize, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabeltaskingTitle))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jButtonRandomize, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExportandSave, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRandomize, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExportandSave, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabeltaskingTitle)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelKitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldKitchenSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDishwashingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDiningSize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHallwaySize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLaundrySize1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelDishwashing, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDining, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelHallway, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelBackGarden, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelFrontGarden, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextFieldBackGardenSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldFrontGardenSize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCourtyard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCourtyardSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelComlab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldComlabSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStaffOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStaffSize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        // Display a confirmation dialog box
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            // Redirect to login
            // Assuming that "login" is the name of your login JFrame
            JFrame login = new LoginPage();
            login.setVisible(true);

            // Close the current JFrame
            // Assuming that "currentFrame" is the name of your current JFrame
            this.dispose();
        } else {
            // Admin clicked "no", do nothing
            return;
        }
    }//GEN-LAST:event_jLabelLogoutMouseClicked

    private void jLabelHomeinTaskingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeinTaskingMouseClicked
        JFrame adminHome = new AdminHome();
        adminHome.setVisible(true);

        // Close the current JFrame
        // Assuming that "currentFrame" is the name of your current JFrame
        this.dispose();

    }//GEN-LAST:event_jLabelHomeinTaskingMouseClicked


    private void jButtonRandomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomizeActionPerformed
        // Retrieve the task sizes from the corresponding text fields

        try {
            // Check if any of the fields are empty
            if (jTextFieldKitchenSize1.getText().isEmpty() || jTextFieldHallwaySize.getText().isEmpty()
                    || jTextFieldDiningSize.getText().isEmpty() || jTextFieldComlabSize1.getText().isEmpty()
                    || jTextFieldFrontGardenSize.getText().isEmpty() || jTextFieldBackGardenSize1.getText().isEmpty()
                    || jTextFieldLaundrySize1.getText().isEmpty() || jTextFieldCourtyardSize1.getText().isEmpty()
                    || jTextFieldStaffSize.getText().isEmpty() || jTextFieldDishwashingSize.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please input values for all required fields.", "Missing Fields", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Parse the task sizes
            int kchenval, hwayval, dineval, clabval, frontgval, backgval, laundryval, courtyardval, officeval, dishwashingval;
            try {
                kchenval = Integer.parseInt(jTextFieldKitchenSize1.getText());
                hwayval = Integer.parseInt(jTextFieldHallwaySize.getText());
                dineval = Integer.parseInt(jTextFieldDiningSize.getText());
                clabval = Integer.parseInt(jTextFieldComlabSize1.getText());
                frontgval = Integer.parseInt(jTextFieldFrontGardenSize.getText());
                backgval = Integer.parseInt(jTextFieldBackGardenSize1.getText());
                laundryval = Integer.parseInt(jTextFieldLaundrySize1.getText());
                courtyardval = Integer.parseInt(jTextFieldCourtyardSize1.getText());
                officeval = Integer.parseInt(jTextFieldStaffSize.getText());
                dishwashingval = Integer.parseInt(jTextFieldDishwashingSize.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input positive integers only for the task sizes.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if any of the sizes are negative
            if (kchenval < 0 || hwayval < 0 || dineval < 0 || clabval < 0 || frontgval < 0
                    || backgval < 0 || laundryval < 0 || courtyardval < 0 || officeval < 0 || dishwashingval < 0) {
                JOptionPane.showMessageDialog(this, "Please input positive integers only for the task sizes.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Connection con = DatabaseConnection.getConnection();
            Statement st = con.createStatement();
            String query = "select * from scholars";
            ResultSet rs = st.executeQuery(query);

            // Add data to ArrayList
            List<Scholar> scholars = new ArrayList<>();
            while (rs.next()) {
                String firstName = rs.getString("FirstName");
                String lastName = rs.getString("LastName");
                Scholar scholar = new Scholar(0, firstName, lastName);
                scholars.add(scholar);
            }

            st.close();
            con.close();

            DefaultTableModel model = (DefaultTableModel) jTableTaskingRandomizer.getModel();
            model.setRowCount(0); // clear the table before populating

            // create a list of scholars with the specified number of entries
            int totalEntries = kchenval + dishwashingval + dineval + hwayval + laundryval + officeval + courtyardval + backgval + frontgval + clabval;
            if (totalEntries <= 0) {
                JOptionPane.showMessageDialog(this, "Please input positive integers for the task sizes.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if there are enough scholars available
            if (scholars.size() < totalEntries) {
                String message = "Not enough scholars available. There are only " + scholars.size() + " scholars to be randomized for the total tasking sizes entered.";
                JOptionPane.showMessageDialog(this, message, "Insufficient Scholars", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // shuffle the list of scholars
            List<Scholar> shuffledScholars = new ArrayList<>(scholars);
            Collections.shuffle(shuffledScholars);

            // Create a list of columns and their corresponding size
            List<String> columns = new ArrayList<>(Arrays.asList("kitchen", "hallway", "dining", "comlab", "frontgarden", "backgarden", "laundry", "courtyard", "office", "dishwashing"));
            List<Integer> sizes = new ArrayList<>(Arrays.asList(kchenval, dishwashingval, dineval, hwayval, laundryval, officeval, courtyardval, backgval, frontgval, clabval));

            // Shuffle the list of columns
            Collections.shuffle(columns);

            int numCols = columns.size();
            List<List<Scholar>> rows = new ArrayList<>();
            Map<Scholar, Integer> assignedScholars = new HashMap<>();
            Map<String, Scholar> lastAssignedScholars = new HashMap<>();

            for (int i = 0; i < numCols; i++) {
                int size = sizes.get(i);
                List<Scholar> column = new ArrayList<>();
                for (int j = 0; j < size; j++) {
                    Scholar scholar = null;
                    do {
                        if (shuffledScholars.size() == 0) {
                            break;
                        }
                        scholar = shuffledScholars.remove(0);
                    } while (assignedScholars.containsKey(scholar)
                            || (lastAssignedScholars.containsKey(columns.get(i)) && lastAssignedScholars.get(columns.get(i)).equals(scholar)));
                    if (scholar != null) {
                        assignedScholars.put(scholar, i);
                        column.add(scholar);
                        lastAssignedScholars.put(columns.get(i), scholar);
                    }
                }
                rows.add(column);
            }

            // populate the table with the shuffled and distributed scholars
            int numRows = rows.stream().mapToInt(List::size).max().orElse(0);
            for (int i = 0; i < numRows; i++) {
                String[] row = new String[numCols];
                for (int j = 0; j < numCols; j++) {
                    if (i < rows.get(j).size()) {
                        Scholar scholar = rows.get(j).get(i);
                        row[j] = scholar.getFirstName() + " " + scholar.getLastName();
                    }
                }
                model.addRow(row);
            }

        } catch (SQLException e1) {
            e1.printStackTrace();
        }

    }//GEN-LAST:event_jButtonRandomizeActionPerformed

    private void jLabelProfileinTaskingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProfileinTaskingMouseClicked
        // Calling the openUserProfile method from the ProfileController class to view user profile
        ProfileController.openUserProfile();
    }//GEN-LAST:event_jLabelProfileinTaskingMouseClicked

    private void jLabelListOfScholarinTaskingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelListOfScholarinTaskingMouseClicked
        if (evt.getClickCount() == 1) { // check if the label is clicked once
            try {
                // create a new instance of ListOfScholars frame
                // create a new instance of ListOfScholars frame
                ListOfScholar listOfScholarFrame = new ListOfScholar(jTableListOfScholars);
                // create a new instance of ListScholarsClickListener and pass the jTableListOfScholars component
                ListScholarsClickListener listScholarsClickListener = new ListScholarsClickListener(listOfScholarFrame.getjTableListOfScholars());
                // call the onClick method to populate the jTableListOfScholars with the list of scholars data
                listScholarsClickListener.onClick();
                // set the ListOfScholars frame visible to the user
                listOfScholarFrame.setVisible(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabelListOfScholarinTaskingMouseClicked

    private void jButtonRandomizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRandomizeMouseClicked


    }//GEN-LAST:event_jButtonRandomizeMouseClicked

    private void jLabelTableAssignmentToolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTableAssignmentToolMouseClicked
        // TODO add your handling code here:
        // Redirect to taskingRandomizer22
        JFrame tableAssignmentTool = new TableArrangements();
        tableAssignmentTool.setVisible(true);

        // Close the current JFrame
        this.dispose();
    }//GEN-LAST:event_jLabelTableAssignmentToolMouseClicked

    private void jButtonExportandSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExportandSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExportandSaveMouseClicked

    private void jButtonExportandSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportandSaveActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Excel File");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            try {
                String filePath = fileChooser.getSelectedFile().getAbsolutePath();
                if (!filePath.endsWith(".xlsx")) {
                    filePath += ".xlsx";
                }


                // Export table data to Excel
                SaveandExportBackend saveAndExportBackend = new SaveandExportBackend();
                saveAndExportBackend.saveResult(filePath, jTableTaskingRandomizer, (DefaultTableModel) jTableTaskingRandomizer.getModel(), columns);

                System.out.println("Excel file saved successfully.");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButtonExportandSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonExportandSave;
    private javax.swing.JButton jButtonRandomize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBackGarden;
    private javax.swing.JLabel jLabelComlab;
    private javax.swing.JLabel jLabelCourtyard;
    private javax.swing.JLabel jLabelDining;
    private javax.swing.JLabel jLabelDishwashing;
    private javax.swing.JLabel jLabelFrontGarden;
    private javax.swing.JLabel jLabelHallway;
    private javax.swing.JLabel jLabelHomeinTasking;
    private javax.swing.JLabel jLabelKitchen;
    private javax.swing.JLabel jLabelLaundry;
    private javax.swing.JLabel jLabelListOfScholarinTasking;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelProfileinTasking;
    private javax.swing.JLabel jLabelStaffOffice;
    private javax.swing.JLabel jLabelTableAssignmentTool;
    private javax.swing.JLabel jLabeltaskingTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTaskingRandomizer;
    private javax.swing.JTextField jTextFieldBackGardenSize1;
    private javax.swing.JTextField jTextFieldComlabSize1;
    private javax.swing.JTextField jTextFieldCourtyardSize1;
    private javax.swing.JTextField jTextFieldDiningSize;
    private javax.swing.JTextField jTextFieldDishwashingSize;
    private javax.swing.JTextField jTextFieldFrontGardenSize;
    private javax.swing.JTextField jTextFieldHallwaySize;
    private javax.swing.JTextField jTextFieldKitchenSize1;
    private javax.swing.JTextField jTextFieldLaundrySize1;
    private javax.swing.JTextField jTextFieldStaffSize;
    // End of variables declaration//GEN-END:variables
}
